package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type StartWithdrawResp struct {
	// Request ID.
	ReqId int64 `json:"req_id,omitempty"`
}
