package swagger
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderBookRetailResp struct {
	// Market e.g.: 'XBTILK'
	Market string `json:"market,omitempty"`
	// Sell items
	Sell []OrderBookRetailRespSell `json:"sell,omitempty"`
	// Buy items
	Buy []OrderBookRetailRespSell `json:"buy,omitempty"`
}
