package swagger
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type RetailSellTokenLimitBody struct {
	Amount string `json:"amount"`
	Limit  string `json:"limit"`
	Pair   string `json:"pair"`
}
