package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Info about free withdrawals.
type WithdrawDetailsRetailRespFeeInfo struct {
	// True if this withdraw will be free by zero withdraw fee, otherwise false
	FreeWithdraw bool `json:"free_withdraw,omitempty"`
	// True if this withdraws fee will be waived, otherwise false
	WaivedWithdraw bool `json:"waived_withdraw,omitempty"`
	// monthly total waived withdrawal fees
	TotalWaives int64 `json:"total_waives,omitempty"`
	// already used monthly waived fees on withdrawals
	UsedWaives int64 `json:"used_waives,omitempty"`
	// source of waived fees (should be: \"ilkbalance\",\"badge\",\"gift\",\"other\" or None.)
	Reason string `json:"reason,omitempty"`
}
