package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type GeneralErrorResponseError struct {
	Code    string `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
