package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type BalanceResp struct {
	// fiat values calculated in this currency (default: usd)
	Fiat string `json:"fiat,omitempty"`
	// total available balance in fiat.
	Total string `json:"total,omitempty"`
	// sum pending interest in fiat.
	AccruingInterestFiat string `json:"accruing_interest_fiat,omitempty"`
	// sum of total interest earned in fiat.
	TotalInterestEarnedFiat string `json:"total_interest_earned_fiat,omitempty"`
	// List of detailed balance entries per coins
	Coins []BalanceRespCoins `json:"coins,omitempty"`
}
