package swagger
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type RetailSellTokenMarketBody struct {
	// Amount to sell.
	Amount string `json:"amount"`
	// Trading pair of the market e.g.: XBTILK.
	Pair string `json:"pair"`
}
