package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type WithdrawDetailsResp struct {
	// List of withdraw details for each supported chain.
	Chains []WithdrawDetailsRespChains `json:"chains,omitempty"`
}
