package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type BalanceRespCoins struct {
	// ticker of coin of the balance
	Ticker string `json:"ticker,omitempty"`
	// amount of available balance in normal format
	Balance string `json:"balance,omitempty"`
	// amount of pending balance (deposit under confirming or pending withdrawal)
	Pending string `json:"pending,omitempty"`
	// locked amount (defined for further functions, but not used in INLOCK WL)
	Locked string `json:"locked,omitempty"`
	// pending interest. (in kind)
	AccruingInterest string `json:"accruing_interest,omitempty"`
	// amount of interest credited since onboarding. (in kind)
	TotalInterestEarned string `json:"total_interest_earned,omitempty"`
	// amount of available in fiat
	BalanceFiat string `json:"balance_fiat,omitempty"`
	// amount of pending balance in fiat
	PendingFiat string `json:"pending_fiat,omitempty"`
	// locked amount in fiat
	LockedFiat string `json:"locked_fiat,omitempty"`
	// pending interest in fiat
	AccruingInterestFiat string `json:"accruing_interest_fiat,omitempty"`
	// amount of interest credited since onboarding in fiat
	TotalInterestEarnedFiat string `json:"total_interest_earned_fiat,omitempty"`
}
