package swagger
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type DepositAddressesRespAddresses struct {
	// ticker of coin
	Ticker string `json:"ticker,omitempty"`
	// chain identifier. Possible results: native, bep2, bep20, erc20, trc20, omni, sol, cardano
	Network string `json:"network,omitempty"`
	// is this address is primary for coin? Only native chain's address can be primary
	Primary bool `json:"primary,omitempty"`
	// address for coin deposits on chain
	Address string `json:"address,omitempty"`
	// additional memo for deposits (only valid on bep2 network)
	Memo string `json:"memo,omitempty"`
}
