package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type WalletHistoryRespEvents struct {
	// Unique ID of the event.
	EvId int64 `json:"ev_id,omitempty"`
	// Time of creation. Unix timestamp in UTC.
	Created int64 `json:"created,omitempty"`
	// Type of event.
	Type_ string `json:"type,omitempty"`
	// Status of withdraw events.
	Status string `json:"status,omitempty"`
	// Amount related to the event. Optional, can be null.
	Amt string `json:"amt,omitempty"`
	// Ticker related to the event. Optional, can be null.
	Ticker string `json:"ticker,omitempty"`
	// Shows the sender of the transfer. Optional, only used in internal/badge transfers
	FromUser string `json:"from_user,omitempty"`
	// Shows the receiver of the transfer. Optional, only used in internal/badge transfers
	ToUser string `json:"to_user,omitempty"`
	// Second amount related to the event. Optional, can be null.
	Amt2 string `json:"amt2,omitempty"`
	// Second ticker related to the event. Optional, can be null.
	Ticker2 string `json:"ticker2,omitempty"`
	// Third amount related to the event. Optional, can be null.
	Amt3 string `json:"amt3,omitempty"`
	// Description related to the event. Can be null.
	Desc string `json:"desc,omitempty"`
}
