package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type WithdrawDetailsRetailRespChains struct {
	// Ticker of the coin
	Ticker string `json:"ticker,omitempty"`
	// Chain identifier
	Network string `json:"network,omitempty"`
	// Short name of chain
	ChainShortName string `json:"chain_short_name,omitempty"`
	// Long name of chain
	ChainLongName string `json:"chain_long_name,omitempty"`
	// True if this is the recommended, primary (native) chain for withdraw, false otherwise.
	IsPrimary bool `json:"is_primary,omitempty"`
	// Withdraw addresses of the user.
	Addresses []WithdrawDetailsRetailRespAddresses `json:"addresses,omitempty"`
	// Minimal withdraw amount.
	MinAmt string `json:"min_amt,omitempty"`
	// Fix withdraw fee in the same coin.
	FeeBase string `json:"fee_base,omitempty"`
	// Fee multiplier in the same coin (fee = fee_base + amount * fee_mult).
	FeeMult string                            `json:"fee_mult,omitempty"`
	FeeInfo *WithdrawDetailsRetailRespFeeInfo `json:"fee_info,omitempty"`
	// Congestion status of the network: \"no\", \"slight\", \"significant\", \"heavy\", \"disabled\".
	Congestion string `json:"congestion,omitempty"`
}
