package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type WithdrawDetailsRespAddresses struct {
	// Address
	Address string `json:"address,omitempty"`
	// User defined description.
	Description string `json:"description,omitempty"`
	// Memo
	Memo string `json:"memo,omitempty"`
	// timestamp if the withdraw address is locked
	LockedUntil int64 `json:"locked_until,omitempty"`
}
