package inlock
/*
 * INLOCK API
 *
 * This is the documentation of the INLOCK API.
 *
 * API version: 1.4.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type OrderIdResp struct {
	// ID of the order
	Orderid int64 `json:"orderid,omitempty"`
}
